<a href="https://colab.research.google.com/github/Mriano29/hotel_demand_forecasting_system/blob/main/Hotel_occupation_preparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **`Notebook 3:` Preparación de datos externos (Ocupación por nacionalidad por hoteles)**

El dataset obtenido del ISTAC presenta una estructura no tabular estándar, muy similar a la observada en el primer dataset analizado anteriormente.

En concreto, incluye:
- Filas iniciales con metadatos (unidades, descripciones, actualización)
- Fechas distribuidas en columnas en lugar de filas
- Valores numéricos almacenados como texto
- Estructura jerárquica (indicador, región, país)

Dado que este formato ya ha sido tratado previamente, se seguirá el mismo enfoque de limpieza:
1. Eliminación de filas irrelevantes
2. Asignación de cabeceras
3. Transformación a formato largo (long format)
4. Conversión de tipos de datos
5. Reestructuración final para análisis y posterior integración

###**Indice**

1. Carga de datos y visualización de primeras columnas
2. Inspección inicial de la estructura
3. Asignación de cabeceras
4. Análisis de estructura tras reconstrucción
5. Filtrado y preparación de datos para Canarias
6. Transformación a formato longitudinal (MELT)
7. Filtrado a Canarias
8. Validación final de estructura
9. Transformación a formato longitudinal (MELT)
10. Exportado de datos

##1 — Carga de datos y visualización de primeras columnas

In [17]:
import pandas as pd

url = "https://raw.githubusercontent.com/Mriano29/hotel_demand_forecasting_system/refs/heads/main/data/raw_data/occupation_by_nationality_hotels.csv"

df_occupation_hotel = pd.read_csv(url)

print(df_occupation_hotel.shape)
df_occupation_hotel.head()

(2540, 227)

,"Pernoctaciones, viajeros alojados, viajeros entrados y estancia media en hoteles según principales nacionalidades. Islas y municipios de Canarias por periodos",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 217,Unnamed: 218,Unnamed: 219,Unnamed: 220,Unnamed: 221,Unnamed: 222,Unnamed: 223,Unnamed: 224,Unnamed: 225,Unnamed: 226
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Last update,"Apr 22, 2026",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Units:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Measure unit (Estancia media): Nights (Units),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Measure unit (Pernoctaciones): Nights (Units),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

##2 — Inspección inicial de la estructura

In [18]:
for i in range(15):
    print(f"\n--- FILA {i} ---")
    print(df_occupation_hotel.iloc[i].values[:10])

--- FILA 0 ---
[nan nan nan nan nan nan nan nan nan nan]

--- FILA 1 ---
['Last update' 'Apr 22, 2026' nan nan nan nan nan nan nan nan]

--- FILA 2 ---
['Units:' nan nan nan nan nan nan nan nan nan]

--- FILA 3 ---
[nan 'Measure unit (Estancia media): Nights (Units)' nan nan nan nan nan
 nan nan nan]

--- FILA 4 ---
[nan 'Measure unit (Pernoctaciones): Nights (Units)' nan nan nan nan nan
 nan nan nan]

--- FILA 5 ---
[nan 'Measure unit (Viajeros alojados): Persons (Units)' nan nan nan nan
 nan nan nan nan]

--- FILA 6 ---
[nan 'Measure unit (Viajeros entrados): Persons (Units)' nan nan nan nan
 nan nan nan nan]

--- FILA 7 ---
[nan nan nan nan nan nan nan nan nan nan]

--- FILA 8 ---
['By: Tourist accommodation = Hotel' nan nan nan nan nan nan nan nan nan]

--- FILA 9 ---
[nan nan nan nan nan nan nan nan nan nan]

--- FILA 10 ---
[nan nan nan nan nan nan nan nan nan nan]

--- FILA 11 ---
[nan nan nan '03/2026' '02/2026' '01/2026' '2025' '12/2025' '11/2025'
 '10/2025']

--- FILA 12 ---
['Estancia media' 'Canary Islands' 'Spain' '3,727934674' '3,7428312'
 '4,142758347' '3,94670572' '3,830239007' '3,867674136' '3,880565479']

--- FILA 13 ---
[nan nan 'World (Spain excluded)' '7,003652106' '6,973487442'
 '7,358561049' '7,331070621' '7,231523854' '7,063721742' '7,224629195']

--- FILA 14 ---
[nan nan 'Germany' '7,90225274' '8,36568218' '8,786074965' '8,568815278'
 '8,839963379' '8,273206037' '8,330081189']

##3 — Asignación de cabeceras

In [19]:
header_row = 11

# Extraer fechas (columnas temporales)
date_cols = df_occupation_hotel.iloc[header_row, 3:].values

# Crear dataset a partir de los datos reales
df_clean = df_occupation_hotel.iloc[header_row + 1:].copy()

# Asignar nombres de columnas
df_clean.columns = ['indicator', 'region', 'country'] + list(date_cols)

df_clean = df_clean.reset_index(drop=True)

df_clean.head()

,indicator,region,country,03/2026,02/2026,01/2026,2025,12/2025,11/2025,10/2025,...,10/2009,09/2009,08/2009,07/2009,06/2009,05/2009,04/2009,03/2009,02/2009,01/2009
0,Estancia media,Canary Islands,Spain,"3,727934674","3,7428312","4,142758347","3,94670572","3,830239007","3,867674136","3,880565479",...,"3,952086163","5,138946821","5,577218402","4,972494328","4,296516657","4,150801742","4,094106204","4,026300668","3,992944526","4,823183267"
1,NaN,NaN,World (Spain excluded),"7,003652106","6,973487442","7,358561049","7,331070621","7,231523854","7,063721742","7,224629195",...,"8,447868717","9,536210568","9,723430827","9,884151728","9,185200423","8,621135991","8,544380964","9,013347924","8,891330556","9,923623353"
2,NaN,NaN,Germany,"7,90225274","8,36568218","8,786074965","8,568815278","8,839963379","8,273206037","8,330081189",...,"9,942361004","10,89067764","10,43125061","11,42888846","10,25437541","9,643084041","9,893489474","10,69675869","10,4902454","11,34743431"
3,NaN,NaN,Belgium,"7,706231922","7,246830239","7,782423039","7,722170614","7,928650208","7,065228557","7,542249558",...,"7,861803757","9,547286822","9,745470286","9,178040678","10,06278027","8,97","7,815826168","9,05896898","9,409010788","10,48359867"
4,NaN,NaN,Denmark,"7,504796985","7,474002923","7,314633735","7,610713369","7,81402183","7,163465325","6,774647126",...,"6,860658771","7,388794567","9,233343959","8,75722161","7,701357466","7,350251123","8,522176871","8,254505998","8,123237278","8,806297587"

##4 — Análisis de estructura tras reconstrucción

In [20]:
df_clean[['indicator', 'region', 'country']].head(20)

,indicator,region,country
0,Estancia media,Canary Islands,Spain
1,NaN,NaN,World (Spain excluded)
2,NaN,NaN,Germany
3,NaN,NaN,Belgium
4,NaN,NaN,Denmark
5,NaN,NaN,France
6,NaN,NaN,Ireland
7,NaN,NaN,Italy
8,NaN,NaN,Norway
9,NaN,NaN,Netherlands
10,NaN,NaN,Poland
11,NaN,NaN,United Kingdom of Great Britain and Northern I...
12,NaN,NaN,Sweden
13,NaN,NaN,Switzerland
14,NaN,NaN,Other countries or regions of the world (Spain...
15,NaN,Lanzarote,Spain
16,NaN,NaN,World (Spain excluded)
17,NaN,NaN,Germany
18,NaN,NaN,Belgium
19,NaN,NaN,Denmark

##5 — Filtrado y preparación de datos para Canarias

In [21]:
df_clean['indicator'] = df_clean['indicator'].ffill()
df_canarias = df_clean[df_clean['region'] == 'Canary Islands'].copy()
df_canarias['indicator'].value_counts()

indicator
Estancia media       1
Pernoctaciones       1
Viajeros alojados    1
Viajeros entrados    1
Name: count, dtype: int64

##6 — Transformación a formato longitudinal (MELT)

###6.1 — Separación de columnas temporales

In [22]:
# Separar columnas no temporales
id_vars = ['indicator', 'region', 'country']

# Columnas temporales (todas las demás)
value_vars = [col for col in df_canarias.columns if col not in id_vars]

len(value_vars), value_vars[:5]

(224, ['03/2026', '02/2026', '01/2026', '2025', '12/2025'])

###6.2 — Aplicación de melt

In [23]:
df_oh_long = df_canarias.melt(
    id_vars=id_vars,
    value_vars=value_vars,
    var_name='date',
    value_name='value'
)

df_oh_long.head()

           indicator          region country     date        value
0     Estancia media  Canary Islands   Spain  03/2026  3,727934674
1     Pernoctaciones  Canary Islands   Spain  03/2026       522731
2  Viajeros alojados  Canary Islands   Spain  03/2026       151258
3  Viajeros entrados  Canary Islands   Spain  03/2026       140220
4     Estancia media  Canary Islands   Spain  02/2026    3,7428312

###6.3 — Conversión de formatos de fechas

In [24]:
# Filtrar solo fechas con formato mensual (contienen "/")
df_oh_long = df_oh_long[df_oh_long['date'].astype(str).str.contains('/')].copy()

# Convertir fechas de forma segura
df_oh_long['date'] = pd.to_datetime(df_oh_long['date'], format='%m/%Y', errors='coerce')

# Convertir valores numéricos (coma → punto)
df_oh_long['value'] = (
    df_oh_long['value']
    .astype(str)
    .str.replace(',', '.', regex=False)
)

df_oh_long['value'] = pd.to_numeric(df_oh_long['value'], errors='coerce')

df_oh_long.dtypes

indicator            object
region               object
country              object
date         datetime64[ns]
value               float64
dtype: object

###6.4 — Validación del dataset

In [25]:
print(f"\nFilas: {df_oh_long.shape[0]}")
print(f"Columnas: {df_oh_long.shape[1]}")

print("\nTIPOS DE DATOS:")
print(df_oh_long.dtypes)

print("\nVALORES NULOS:")
print(df_oh_long.isnull().sum().sort_values(ascending=False))

print("\nDUPLICADOS:")
print(df_oh_long.duplicated().sum())

print("\nCOLUMNAS:")
print(df_oh_long.columns.tolist())

Filas: 828
Columnas: 5

TIPOS DE DATOS:
indicator            object
region               object
country              object
date         datetime64[ns]
value               float64
dtype: object

VALORES NULOS:
value        4
indicator    0
region       0
country      0
date         0
dtype: int64

DUPLICADOS:
0

COLUMNAS:
['indicator', 'region', 'country', 'date', 'value']

###6.5 — Validación de datos nulos

Tras revisar manualmente las filas afectadas y comprobar sus fechas asociadas, se concluyó que dichos registros no formarán parte del rango temporal utilizado en el dataset final del proyecto. Por este motivo, los valores nulos se mantienen sin modificación, ya que no afectan al proceso de integración, entrenamiento ni validación del modelo.

In [26]:
df_oh_long[df_oh_long["value"].isna()]

             indicator          region country       date  value
308     Estancia media  Canary Islands   Spain 2020-04-01    NaN
309     Pernoctaciones  Canary Islands   Spain 2020-04-01    NaN
310  Viajeros alojados  Canary Islands   Spain 2020-04-01    NaN
311  Viajeros entrados  Canary Islands   Spain 2020-04-01    NaN

###6.6 — Transformación a formato ancho

In [27]:
df_oh_wide = df_oh_long.pivot_table(
    index='date',
    columns='indicator',
    values='value'
)

df_oh_wide.head()

indicator,Estancia media,Pernoctaciones,Viajeros alojados,Viajeros entrados
date,,,,
2009-01-01,4.823183,563097.0,140565.0,116748.0
2009-02-01,3.992945,448787.0,123116.0,112395.0
2009-03-01,4.026301,518507.0,139405.0,128780.0
2009-04-01,4.094106,719793.0,185512.0,175812.0
2009-05-01,4.150802,704362.0,190303.0,169693.0

###6.7 — Limpieza de nombres de columnas

In [28]:
import unicodedata

def clean_column(col):
    col = col.strip().lower().replace(' ', '_')
    col = ''.join(
        c for c in unicodedata.normalize('NFD', col)
        if unicodedata.category(c) != 'Mn'
    )
    return col

df_oh_wide.columns = [clean_column(col) for col in df_oh_wide.columns]

df_oh_wide.columns = df_oh_wide.columns.str.replace('.', '_', regex=False)

df_oh_wide.head()

,estancia_media,pernoctaciones,viajeros_alojados,viajeros_entrados
date,,,,
2009-01-01,4.823183,563097.0,140565.0,116748.0
2009-02-01,3.992945,448787.0,123116.0,112395.0
2009-03-01,4.026301,518507.0,139405.0,128780.0
2009-04-01,4.094106,719793.0,185512.0,175812.0
2009-05-01,4.150802,704362.0,190303.0,169693.0

## 7 — Exportado de datos

In [29]:
df_oh_wide.to_csv("hotel_occupation_prepared.csv", index=False)